name: Run tests for Python scripts
permissions:
  contents: read

on:
  pull_request:
    branches: main
    paths:
      - 'src/*.py'
      - 'src/requirements.txt'
  workflow_dispatch:

jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Install uv 🐍
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b  #v6.6.0
        with:
          version: "0.5.30"

      - name: Install dependencies 📦️
        run: |
          uv venv
          uv pip install -r src/requirements.txt

      - name: Run tests 🧪
        run: |
          uv run --module pytest src/get_clades_to_model.py -s
          uv run --module pytest src/get_location_date_counts.py -s
          uv run --module pytest src/get_target_data.py -s
